In [ ]:
import numpy as np

#to know the numpy version
print(np.__version__)

In [ ]:
#Task 1: Basic Numpy
'''Complete the following short basic NumPy tasks.'''

# 1. Create a 1D array of numbers from 0 to 9

import numpy as np

x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Array from 0 to 9: ")
print(x)




In [3]:
# 2. Convert a 1D array to a 2D array with 2 rows

import numpy as np
y = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(y)
x = y.reshape(2,4)
print(x)


[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [4]:
# 3. Write a NumPy program to create an array of the integers from 30 to 70
import numpy as np
arr = np.arange(30, 71)
print("Array of integers from 30 to 70")

print(arr)



Array of integers from 30 to 70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [ ]:
# 4. Write a NumPy program to append values to the end of an array.
import numpy as np

x = [1, 2, 3, 4, 5]
print("Main array: ", x)


#to append new numbers to the main array

x = np.append(x, [6, 7, 8, 9, 10])
print("Combined array is: ", x)

In [ ]:
#Extension

#1. Write a NumPy program to find the number of rows and columns of a given matrix.
import numpy as np
x = np.arange(1,11).reshape((2,5))
print("Main Matrix is: ", x)

print("Number of rows and colume of matrix is : ")
print(x.shape)

In [5]:
#2. Write a NumPy program to create an array of all the even integers from 30 to 70.
import numpy as np
x = np.arange(30,71,2)
print("The Array of all the even integers from 30 to 70 are: ", x)


The Array of all the even integers from 30 to 70 are:  [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [6]:
#3. Write a NumPy program to convert a list and tuple into arrays.
import numpy as np
list = [1, 2, 3, 4, 5]
#convert list to an array
print("List to array: ")
print(np.asarray(list))


tuple = (6, 7, 8, 9, 10)
#convert tuple to an array
print("Tuple to array: ")
print(np.asarray(tuple))


List to array: 
[1 2 3 4 5]
Tuple to array: 
[ 6  7  8  9 10]


In [7]:
#4. Write a NumPy program to create a structured array from given student name, height,

#class and their data types. Now sort the array on height.

#set the data types

import numpy as np
dataType = [("name", "S15"), ("class", int), ("height", float)]
students = [("Jason", 3, 30.2), ("Joel", 4, 35.6), ("Jubilee", 5, 40.20), ("Joyce", 6, 50.20)]

#create the array
students_details = np.array(students, dtype=dataType)
print(students_details)
#sorting by height)
print(np.sort(students_details, order="height"))

[(b'Jason', 3, 30.2) (b'Joel', 4, 35.6) (b'Jubilee', 5, 40.2)
 (b'Joyce', 6, 50.2)]
[(b'Jason', 3, 30.2) (b'Joel', 4, 35.6) (b'Jubilee', 5, 40.2)
 (b'Joyce', 6, 50.2)]


In [8]:
#Complete the following short Mathematics tasks

#1. Write a NumPy program to add, subtract, multiply, divide arguments elementwise.

import numpy as np

#addition
print("Add: ")
x = np.add(5.0, 6.0)

print(x)

#subtraction
print("Subtract: ")
i = np.subtract(5.0, 6.0)
print(i)

#Multiplication
print("Multiply: ")
y = np.multiply(5.0, 6.0)
print(y)

#division
print("Divide: ")
a = np.divide(5.0, 6.0)
print(a)


Add: 
11.0
Subtract: 
-1.0
Multiply: 
30.0
Divide: 
0.8333333333333334


In [9]:
#2. Write a NumPy program to round elements of the array to the nearest integer.
import numpy as np
x = np.array([11.0, -1.0, 30.0, 0.8333334])
print(x)
#round elements
x = np.rint(x)
print(x)

[11.        -1.        30.         0.8333334]
[11. -1. 30.  1.]


In [10]:
#3. Write a NumPy program to get true division of the element-wise array inputs.
import numpy as np
a = np.arange(8)
print("Main Array: ", a)

print(np.true_divide(a, 2))


Main Array:  [0 1 2 3 4 5 6 7]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5]


In [ ]:
#Extension

#1. Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix

#product.

#use random to select numbers at random

import numpy as np
a = np.random.random((5,3))
print("Array One is: ", a)


b = np.random.random((3,2))
print("Array Two is: ", b)


c = np.dot(a,b)
print("Product of the two arrays is: ", c)

In [ ]:
#2. Write a NumPy program to create a random array with 1000 elements and compute the

# average, variance, standard deviation of the array elements.
import numpy as np
x = np.random.randn(1000)

#calculate mean
print("The Average of array elements is: ")
mean = x.mean()
print(mean)

#Calculate the Statndard deviation
print("The Standard Deviation of the array elements is: ")
std = x.std()
print(std)

#Calculate the Variance
print("The Variance of the array elements is: ")
var = x.var()
print(var)


In [ ]:
#3. Write a NumPy program to calculate round, floor, ceiling, truncated and round (to the

#given number of decimals) of the input, elementwise of a given array.
import numpy as np
a = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6])
print("Main Array: ")
print(a)

# calculate the round, floor, ceiling, truncated
r1 = np.around(a)
r2 = np.floor(a)
r3 = np.ceil(a)
r4 = np.trunc(a)
r5 = [round(elem) for elem in a]


print("\naround: ", r1)
print("floor: ", r2)
print("ceil: ", r3)
print("trunc: ", r4)
print("round: ", r5)

In [11]:

'''4. Write a Python program to find the maximum and minimum value of 1D array.

create a 1D array'''
import numpy as np
x = np.array([1, 2, 3,
             5, 6, 7])
#find the maximum element in the array
maximum_element = np.amax(x)

#find minimum element

minimum_element = np.amin(x)

#print Outputs

print("Main Array: ", x)
print("Maximum Element:", maximum_element)
print("Minimum Element:", minimum_element)

Main Array:  [1 2 3 5 6 7]
Maximum Element: 7
Minimum Element: 1
